# SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note

header-y += msm_cam_sensor.h
header-y += msm_camera.h
header-y += msm_camsensor_sdk.h
header-y += msm_fd.h
header-y += msm_isp.h
header-y += msm_jpeg.h
header-y += msm_jpeg_dma.h
header-y += msmb_camera.h
header-y += msmb_generic_buf_mgr.h
header-y += msmb_isp.h
header-y += msmb_ispif.h
header-y += msmb_pproc.h
header-y += radio-iris.h
header-y += radio-iris-commands.h
header-y += synx.h
